package crdt

import (
	"encoding/hex"
	"encoding/json"
	"os"
	"testing"
)

// Cross-language conformance for PRELIM construction of the core types, against
// genuine yjs@13.6.x output. Fixtures are generated by
// testutil/gen_fixtures_prelim.js (`make fixtures`).
//
// Each fixture is an "author" case, the same shape gen_fixtures_yxml.js uses:
// Yjs ran a scripted build with a PINNED clientID; the Go replay below performs
// the identical sequence with the same clientID and must produce byte-identical
// V1 bytes. Every sequence builds its subtree DETACHED and attaches it last,
// which is what forces the container's clock to precede its children's —
// the wire-ordering corner these constructors exist to get right.

type prelimFixture struct {
	Name         string `json:"name"`
	Description  string `json:"description"`
	ClientID     uint64 `json:"clientID"`
	UpdateV1     string `json:"updateV1"`
	ExpectedJSON string `json:"expectedJSON"`
}

func loadPrelimFixtures(t *testing.T) []prelimFixture {
	t.Helper()
	raw, err := os.ReadFile("testdata/prelim_yjs_fixtures.json")
	if err != nil {
		t.Fatalf("reading fixtures (run `make fixtures`): %v", err)
	}
	var doc struct {
		Fixtures []prelimFixture `json:"fixtures"`
	}
	if err := json.Unmarshal(raw, &doc); err != nil {
		t.Fatal(err)
	}
	if len(doc.Fixtures) == 0 {
		t.Fatal("no fixtures loaded")
	}
	return doc.Fixtures
}

// builders replay each fixture's build sequence exactly.
var prelimBuilders = map[string]func(*Doc){
	"map_with_text_child": func(doc *Doc) {
		cells := doc.GetArray("cells")
		doc.Transact(func(txn *Transaction) {
			cell := NewMapPrelim()
			src := NewTextPrelim()
			src.Insert(txn, 0, "coach note", nil)
			cell.Set(txn, "cell_type", "markdown")
			cell.Set(txn, "source", src)
			cell.Set(txn, "metadata", NewMapPrelim())
			cells.PushType(txn, cell)
		})
	},
	"text_child_only": func(doc *Doc) {
		root := doc.GetArray("root")
		doc.Transact(func(txn *Transaction) {
			t := NewTextPrelim()
			t.Insert(txn, 0, "hello", nil)
			root.PushType(txn, t)
		})
	},
	"two_cells_pushed_in_sequence": func(doc *Doc) {
		cells := doc.GetArray("cells")
		doc.Transact(func(txn *Transaction) {
			for _, text := range []string{"first cell", "second cell"} {
				cell := NewMapPrelim()
				src := NewTextPrelim()
				src.Insert(txn, 0, text, nil)
				cell.Set(txn, "source", src)
				cells.PushType(txn, cell)
			}
		})
	},
	"pushtype_after_plain_values": func(doc *Doc) {
		root := doc.GetArray("root")
		doc.Transact(func(txn *Transaction) {
			root.Push(txn, []any{"a"})
			m := NewMapPrelim()
			m.Set(txn, "k", "v")
			root.PushType(txn, m)
		})
	},
	"pushtype_after_tombstone": func(doc *Doc) {
		root := doc.GetArray("root")
		doc.Transact(func(txn *Transaction) {
			root.Push(txn, []any{"a"})
			root.Delete(txn, 0, 1)
			m := NewMapPrelim()
			m.Set(txn, "k", "v")
			root.PushType(txn, m)
		})
	},
	"array_nested_in_map": func(doc *Doc) {
		root := doc.GetArray("root")
		doc.Transact(func(txn *Transaction) {
			outer := NewMapPrelim()
			inner := NewArrayPrelim()
			inner.Push(txn, []any{"one", "two"})
			outer.Set(txn, "outputs", inner)
			root.PushType(txn, outer)
		})
	},
}

func TestPrelimYjsConformanceDecode(t *testing.T) {
	// ygo must apply genuine Yjs bytes and reach the same canonical JSON.
	for _, f := range loadPrelimFixtures(t) {
		t.Run(f.Name, func(t *testing.T) {
			update, err := hex.DecodeString(f.UpdateV1)
			if err != nil {
				t.Fatal(err)
			}
			doc := New()
			if err := doc.ApplyUpdate(update); err != nil {
				t.Fatalf("applying yjs update: %v", err)
			}
			assertSameJSON(t, doc, f.ExpectedJSON)
		})
	}
}

func TestPrelimYjsConformanceAuthorByteIdentical(t *testing.T) {
	// The strong claim: building the same shape in Go, detached and attached
	// last, produces the SAME BYTES Yjs produced.
	for _, f := range loadPrelimFixtures(t) {
		t.Run(f.Name, func(t *testing.T) {
			build, ok := prelimBuilders[f.Name]
			if !ok {
				t.Fatalf("no Go builder for fixture %q", f.Name)
			}
			doc := New(WithClientID(ClientID(f.ClientID)))
			build(doc)

			got := hex.EncodeToString(doc.EncodeStateAsUpdate())
			if got != f.UpdateV1 {
				t.Errorf("V1 bytes differ from yjs@13.6.x\n go  = %s\n yjs = %s", got, f.UpdateV1)
			}
			assertSameJSON(t, doc, f.ExpectedJSON)
		})
	}
}

// assertSameJSON compares a doc's canonical JSON against the fixture's, keyed by
// root name so map ordering cannot make the comparison flaky.
func assertSameJSON(t *testing.T, doc *Doc, expected string) {
	t.Helper()
	var want map[string]any
	if err := json.Unmarshal([]byte(expected), &want); err != nil {
		t.Fatal(err)
	}
	for root := range want {
		b, err := doc.GetArray(root).ToJSON()
		if err != nil {
			t.Fatalf("ToJSON(%s): %v", root, err)
		}
		var gotRoot, wantRoot any
		if err := json.Unmarshal(b, &gotRoot); err != nil {
			t.Fatal(err)
		}
		wb, _ := json.Marshal(want[root])
		if err := json.Unmarshal(wb, &wantRoot); err != nil {
			t.Fatal(err)
		}
		g, _ := json.Marshal(gotRoot)
		w, _ := json.Marshal(wantRoot)
		if string(g) != string(w) {
			t.Errorf("root %q:\n got  %s\n want %s", root, g, w)
		}
	}
}
